version: '3.8'
services:
  pgmigrationsdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: pgmigrations
    ports:
        - 5432:5432